_target_: src.models.tt_method_module.T3ALModule

split: 0
dataset: anet
setting: 50
video_path:

net:
  _target_: src.models.components.tt_method.T3ALNet
  dataset: ${model.dataset}
  split: ${model.split}
  setting: ${model.setting}
  ltype: BYOLfeat
  refine_with_captions: True
  text_projection: True
  text_encoder: False
  image_projection: True
  logit_scale: True
  normalize: False
  steps: 15
  kernel_size: 50
  stride: 200
  randper: 10
  p: 0.8
  n: 20
  remove_background: False
  visualize: False  
  video_path: ${model.video_path}

optimizer:
  _target_: torch.optim.Adam
  _partial_: true 
  lr: 0.00001
  weight_decay: 0.0001
